
export const CHANGE_USER_STATE = 'CHANGE_USER_STATE';
export const GAME_READY_STATUS = 'GAME_READY_STATUS';
export const SEND_ANSWERS = `SEND_ANSWERS`;
export const STARTING_ROUND = `STARTING_ROUND`;
export const UPDATE_ROOM = `UPDATE_ROOM`;
export const ROUND_LETTER = `ROUND_LETTER`;
export const UPDATE_GAME = `UPDATE_GAME`;
export const ROUND_START = `ROUND_START`;
export const QUESTIONABLE_ANSWERS = `QUESTIONABLE_ANSWERS`;
export const QUESTIONABLE_ANSWERS_SENT = `QUESTIONABLE_ANSWERS_SENT`;
export const QUESTIONABLE_ANSWERS_SENT_NOT_VOTED = `QUESTIONABLE_ANSWERS_SENT_NOT_VOTED`;
export const STARTING_GAME = `STARTING_GAME`;
export const WAITING_TIME = `WAITING_TIME`;
export const UPDATE_SCOREBOARD = `UPDATE_SCOREBOARD`;